### ISSUE TITLE
scenario section

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#10]
This is kinda what I'm thinking so far? It would allow us to incorporate the drop-downs. 

<img width="775" alt="screen shot 2016-09-07 at 11 04 10 pm" src="https://cloud.githubusercontent.com/assets/1656046/18336740/7af18232-754f-11e6-819f-18700b74adb6.png">

**Comment by danmdoh** [comment]
That should do nicely! I'll take a stab at it today.

**Comment by danmdoh** [comment]
updated with latest commit to master — probably needs a bit of work still but it's in!
