### ISSUE TITLE
Income level

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#11]
So it's a bit of a blur, but I'm fairly sure that I pulled the income data from the "the per capita income" at http://www.deptofnumbers.com/income/illinois/chicago/ which pulls from the American Community Survey (http://www.census.gov/programs-surveys/acs/)

For the family section I just doubled it. Probably not the best methodology. 

It would be fairly easy to calculate and pull different averages. 

Thoughts @danmdoherty ?

**Comment by danmdoh** [comment]
this is definitely worth looking into. a good initial research item for when we pick this up again.
