### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#12]
We're going to need something better than the github.io url at some point.

**Comment by amycesal** [comment]
#### Options:

| URL | Price |
| --- | :-: |
| 50-30-20.design | $6.88/year |
| 50-30-20.io | $32.88/year |
| 50-30-20.financial | $39.88/year |
| 50-30-20.site | $0.88/year |
| 50-30-20.fyi | $16.88/year |
| 50-30-20.us | $0.88/year |
| financiallitmustest.site | $0.88/year |

what do you think @danmdoherty

**Comment by amycesal** [comment]
| 50-30-20.io   | $32.88/year     |

**Comment by danmdoh** [comment]
fiftythirtytwenty.com | $8.88 / yr
