### ISSUE TITLE
Scenario width need to be the same as graphs

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#15]

**Comment by amycesal** [comment]
Location should align to the scenario word at the left too.

**Comment by danmdoh** [comment]
Okay, this is adjusted, but has generated some new weirdness with the alignment of the map and family images under _location_ and _household_. Can we combine this with https://github.com/amycesal/50-30-20/issues/10 and maybe get a view of what the Scenario and Ideal sections look like together?
