### ISSUE TITLE
gap of white space on the sides

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#19]
Probably some HTML/CSS magic needs to happen to get rid of this bugger, and just go full bleed. 

<img width="45" alt="screen shot 2016-09-23 at 5 49 20 pm" src="https://cloud.githubusercontent.com/assets/1656046/18803502/1a6ee71a-81b6-11e6-9db3-d86c2ab91cfe.png">

**Comment by danmdoh** [comment]
Resolved with 604999202d49e286a91642976551f31db985e201
