### ISSUE TITLE
Showing where the income level is compared to the rest on a graph

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#24]
Some sort of bar graph to show the income distribution of the area, and highlights where the selected number falls in this range.

**Comment by amycesal** [comment]
This is being incorporated into the layout as a histogram. 

<img width="415" alt="screen shot 2016-10-11 at 10 15 01 pm" src="https://cloud.githubusercontent.com/assets/1656046/19296316/3fa10998-9000-11e6-868f-34caf7b32d1e.png">

**Comment by danmdoh** [comment]
ongoing, reassigning to me

**Comment by danmdoh** [comment]
dupe of https://github.com/amycesal/50-30-20/issues/47
