### ISSUE TITLE
Make production pngs of the map and family/single icons

### ISSUE THREAD

**Issue by danmdoh** [amycesal/50-30-20#28]
... with transparent backgrounds, and at 68px height. Will an image for each household type, and an image for each city. Thank you!

Examples:
http://danmdoherty.com/test/50-30-20/img/fam.png
http://danmdoherty.com/test/50-30-20/img/map.png

**Comment by amycesal** [comment]
Take these for a spin and let me know what I need to change. 

![storyboards_02_1-adult](https://cloud.githubusercontent.com/assets/1656046/19296219/a659ce78-8fff-11e6-9064-d55421dd22ec.png)
![storyboards_02_2-adult-2-kid](https://cloud.githubusercontent.com/assets/1656046/19296221/a65a17de-8fff-11e6-94f8-1b935a03af3d.png)
![storyboards_02_baltimore-map](https://cloud.githubusercontent.com/assets/1656046/19296222/a65ae448-8fff-11e6-9b9b-3f6ee69d7fa2.png)
![storyboards_02_chicago-map](https://cloud.githubusercontent.com/assets/1656046/19296220/a65a224c-8fff-11e6-84a1-3edfaea07aaf.png)

**Comment by danmdoh** [comment]
completed with c90fc1e787d4060fc840266abb6cc3f70f9aae02 and 8ea1040f8db113671af250cff43601b4765e655f
