### ISSUE TITLE
new hex colors

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#31]
<img width="205" alt="screen shot 2016-10-11 at 6 43 44 pm" src="https://cloud.githubusercontent.com/assets/1656046/19292575/ada771a2-8fe2-11e6-857f-567386517d52.png">
<img width="285" alt="screen shot 2016-10-11 at 6 43 38 pm" src="https://cloud.githubusercontent.com/assets/1656046/19292576/adab182a-8fe2-11e6-9458-0b9eefd6ad2c.png">
<img width="373" alt="screen shot 2016-10-11 at 6 43 22 pm" src="https://cloud.githubusercontent.com/assets/1656046/19292577/adab5f38-8fe2-11e6-8e69-b822f1e56cdb.png">

<img width="295" alt="screen shot 2016-10-11 at 6 44 54 pm" src="https://cloud.githubusercontent.com/assets/1656046/19292593/d2ecc73c-8fe2-11e6-9fa8-f0a55556f390.png">
# 65B68A
#297676
# 0C3758
# F9A132
# 5A5B5D
# 115AA0 (for links and click-able things)

**Comment by amycesal** [comment]
Minty stripes: #B8DBC7

**Comment by danmdoh** [comment]
updated with c3d584d694b8f62a8154bd6f18df9b6be4ff1f79
