### ISSUE TITLE
Add new buttons

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#43]
<img width="1220" alt="screen shot 2016-10-18 at 8 52 53 pm" src="https://cloud.githubusercontent.com/assets/1656046/19502807/e606be9e-9574-11e6-975a-016b34fa1681.png">

Add links to about page and to elizabeth warren.

**Comment by danmdoh** [comment]
added a while back, last relevant commit: b5828f5fc334eb602c8d07173ee3747c2ac7d66d
