### ISSUE TITLE
New conclusion box

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#44]
Color for gold text: #DD912C
Color for red text: #993438

I'll push the 3 new icons
### Under 50%

<img width="757" alt="screen shot 2016-10-22 at 8 07 07 pm" src="https://cloud.githubusercontent.com/assets/1656046/19623567/4f11effa-9893-11e6-940b-5fe2c3406677.png">

Following 50-30-20 is basically possible possible in this situation. The average needs of this household are under 50%. The household needs to stay within the average, and control their spending on their wants.
### Over 50%

<img width="764" alt="screen shot 2016-10-22 at 7 58 20 pm" src="https://cloud.githubusercontent.com/assets/1656046/19623573/86af1cd0-9893-11e6-8f3c-301c819de0a6.png">

Following 50-30-20 isn't possible in this situation. The average needs of this household exceed 50% of the income by 38% which reduces the ability for this household to save for the future.
### Over 100%

<img width="766" alt="screen shot 2016-10-22 at 7 58 32 pm" src="https://cloud.githubusercontent.com/assets/1656046/19623578/8ba1e132-9893-11e6-9025-6a1be6009de5.png">

Following 50-30-20 is virtually impossible in this situation. The average needs of this household exceed the income. This harms the household’s ability to not only save for the future, but take care of their necessities.

**Comment by amycesal** [comment]
Your turn @danmdoherty

**Comment by danmdoh** [comment]
updated with eaa2ffc82b61a9b080d2ad71714cea1b9be1e26e
