### ISSUE TITLE
get rid of the "+" on the needs breakdown graphs

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#50]
this is leftover from the print version, but it no longer makes sense because we automate in the next chunk.

User feedback from Erin Simpler.

**Comment by amycesal** [comment]
@danmdoherty where in the code does this live?

**Comment by danmdoh** [comment]
These are in main.js in the draw function, since we need to construct the string each time — resolved with https://github.com/amycesal/50-30-20/commit/1cdb0e0c881970c369929405cf5b4fc59d3ed5bb
