### ISSUE TITLE
White lines on the first 50/30/20 line

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#56]
<img width="424" alt="screen shot 2017-02-08 at 9 33 56 am" src="https://cloud.githubusercontent.com/assets/1656046/22741605/c12bed0e-ede1-11e6-90bb-23ea50d5ac3f.png">

**Comment by danmdoh** [comment]
I'm not sure I can see this issue — could you clarify?

**Comment by amycesal** [comment]
There should be white lines between the colors in the "bar graph". Does that make sense @danmdoherty ?

**Comment by amycesal** [comment]
<img width="424" alt="c12bed0e-ede1-11e6-90bb-23ea50d5ac3f" src="https://cloud.githubusercontent.com/assets/1656046/22760641/5e53ff02-ee25-11e6-97d1-e757be60f82e.png">

**Comment by danmdoh** [comment]
ooooo yeah ok, no problem, will add
