### ISSUE TITLE
Median income is wrong for selected situations

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#58]
It's displaying **$69.402/year** for Baltimore and Oakland, which is not correct

<img width="1024" alt="screen shot 2017-02-08 at 9 50 01 am" src="https://cloud.githubusercontent.com/assets/1656046/22742242/08e78106-ede4-11e6-8bbd-cb28c8d2b569.png">

**Comment by danmdoh** [comment]
Fixed!
