### ISSUE TITLE
Smooth gradient vs. steps

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#6]
<img width="742" alt="screen shot 2016-09-07 at 9 28 43 pm" src="https://cloud.githubusercontent.com/assets/1656046/18335144/a7fbacb0-7542-11e6-9cdd-57db55983075.png">

Instead of the gradient being smooth, it's suppose to represent the 50/30/20 colors in 3 distinct steps. This could still be done with the gradient, just the start and end steps are the same color. Make sense? 

Hex values: 
# C8C1B4
# C0B5AC
# BCB0AE

Side note: this is the best color dropper that I've found and it's SUPER USEFUL: 
http://www.code-line.com/artdirectorstoolkit/

**Comment by danmdoh** [comment]
@amycesal updated! latest code on gh-pages as well as master. I set opacity of the background to 0.18, let me know if there's a value you prefer and I'll update it.
