### ISSUE TITLE
source for childcare not appearing

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#67]
It's in the html, but not displaying. 

<img width="1166" alt="screen shot 2017-02-13 at 11 35 29 pm" src="https://cloud.githubusercontent.com/assets/1656046/22931490/cd84da4c-f292-11e6-98e5-e70b2ccf63eb.png">

**Comment by danmdoh** [comment]
fixed in https://github.com/amycesal/50-30-20/commit/000e22b83d36b7b54c35808ddce4c056acb9473d
