### ISSUE TITLE
Not enough space above needs breakdown graph

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#68]
It should scroll to the top of the graph title and feel like a "new screen" instead of leaving part of the previous screen still in view. Yes, there will be white space at the bottom, but it will be filled in when more parts come in like the verdict. 

<img width="1237" alt="screen shot 2017-02-13 at 11 35 13 pm" src="https://cloud.githubusercontent.com/assets/1656046/22931562/1890aa0c-f293-11e6-9b90-9a21aa9483d8.png">

**Comment by danmdoh** [comment]
To clarify: you're looking for more space _below_ the needs graph, which would push it _up_ in the viewport, yes?

So the thing about this is, we can tune the amount of white space below each section, but it's going to look different on different screens. I've gone ahead and added some code that adds whitespace below each section to make it _more likely_ that the next section is higher in the viewport after you click a scrollcue — the amount of whitespace is a fraction of the screen height, so it's kind of responsive... but I think we need to talk this one through. Let's discuss on our call tomorrow.
