### ISSUE TITLE
Charts not reloading when window/viewport is resized. 

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#7]
@Polisurgist had tips.

**Comment by amycesal** [comment]
@bchartoff can you help? I know you started sleepily started rambling things off like reload metadata in the head with javascript....

**Comment by bchartoff** [comment]
I was babbling about a different kind of issue, this is more about js to redraw the graphic when the window is resized. See PR #26

**Comment by bchartoff** [comment]
(PS This is looking great!)

**Comment by danmdoh** [comment]
Resolved with https://github.com/amycesal/50-30-20/pull/26 thanks Ben!

**Comment by bchartoff** [comment]
HAPPY BIRTHDAY @amycesal !
