### ISSUE TITLE
Better fail state for blank scenario inputs

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#71]
Ideally it should even run, and there should be some sort of error that highlights what you need to select. 

<img width="446" alt="screen shot 2017-02-21 at 9 38 02 pm" src="https://cloud.githubusercontent.com/assets/1656046/23194788/299c07f6-f87e-11e6-8ece-9098c3f1a941.png">

**Comment by danmdoh** [comment]
Fixed!
