### ISSUE TITLE
Check all median income etc. numbers in prescribed scenarios

### ISSUE THREAD

**Issue by danmdoh** [amycesal/50-30-20#78]
Boise, Chicago, Philadelphia
Full family, single male, single mother 1 child

**Comment by danmdoh** [comment]
Okay, these are updated... do the numbers seem right though? It feels like the married couple w/ 2 kids is treated as a two-income household in some areas (Boise) and a one-income household in others (Baltimore)... @amycesal

**Comment by amycesal** [comment]
Yeah this is right in the data. I think it's because households with kids are more likely to be dual or single income in different areas.
