### ISSUE TITLE
Adding white icons to all the previous chunks

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#8]
<img width="557" alt="screen shot 2016-09-07 at 10 06 02 pm" src="https://cloud.githubusercontent.com/assets/1656046/18335736/5a4f2758-7547-11e6-97dd-0495e1e07ebb.png">

**Comment by danmdoh** [comment]
done! pushed to gh-pages, so please go ahead and have a look. @amycesal one note: the icons _might_ be too dark? let me know the correct hex value and I'll update them. Thanks!

**Comment by amycesal** [comment]
White and 70% opacity.

**Comment by danmdoh** [comment]
fixed!
