### ISSUE TITLE
Language update needed — open scenario selection

### ISSUE THREAD

**Issue by danmdoh** [amycesal/50-30-20#80]
![screen shot 2017-02-23 at 9 24 17 am](https://cloud.githubusercontent.com/assets/4466572/23270798/eb27ceb0-f9a9-11e6-90a2-4b2da971b0f1.png)

**Comment by danmdoh** [comment]
How about for all instances we just replace "average" with "typical"? So this title would become something like "Is following the 50/30/20 guideline possible for a typical American household?"

**Comment by amycesal** [comment]
done.
