### ISSUE TITLE
dotted white line over text

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#9]
<img width="130" alt="screen shot 2016-09-07 at 9 55 15 pm" src="https://cloud.githubusercontent.com/assets/1656046/18335748/703b1c52-7547-11e6-9975-a0d8be01bd4f.png">

**Comment by danmdoh** [comment]
fixed in latest yay!
![screen shot 2016-09-12 at 2 33 25 pm](https://cloud.githubusercontent.com/assets/4466572/18453833/ec00ae22-78f5-11e6-9bf8-dcc6c52119ec.png)
